In [1]:
import numpy as np

# Let us also import plotting library
import matplotlib.pyplot as plt 

### Converting Python array-like objects.

# 1D array from list, shape (4, ).
x_1d = np.array([1, 3, 5, 7])

# 2D array from combination of lists and tuples, shape (3, 3).
x_2d = np.array([(1, 1, 1), [2, 2, 2], (3, 3, 3)])

# Print the results.
print(f'x_1d:\n{x_1d}\n')
print(f'x_2d:\n{x_2d}\n')

x_1d:
[1 3 5 7]

x_2d:
[[1 1 1]
 [2 2 2]
 [3 3 3]]



In [9]:
### Using built-in functions provided by NumPy.

# 2D array of zeros, 2 rows, 3 columns.
x_zeros = np.zeros((2, 3))

# 3D array of ones, shape (2, 3, 4) - 2 matrices of 3 rows and 4 columns.
x_ones = np.ones((2, 3, 4))

# Identity matrix with 4 rows and 4 columns.
x_identity = np.eye(4)

# Sequence of numbers from 5 to 11 (11 not included) with step 1.
x_seq = np.arange(5, 11)

# Sequence of ones of the same shape as `x_zeros`.
x_ones_as_zeros = np.ones_like(x_zeros)


# Print the results.
print(f'x_zeros:\n{x_zeros}\n')
print(f'x_ones:\n{x_ones}\n')
print(f'x_identity:\n{x_identity}\n')
print(f'x_seq:\n{x_seq}\n')
print(f'x_ones_as_zeros:\n{x_ones_as_zeros}\n')

x_zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

x_ones:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

x_identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

x_seq:
[ 5  6  7  8  9 10]

x_ones_as_zeros:
[[1. 1. 1.]
 [1. 1. 1.]]



In [10]:
# Create an array of 32bit integers.
x_int = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Cast integer array to 32 bit float array.
x_float = x_int.astype(np.float32)

# Print results.
print(f'Array x_int has data type {x_int.dtype}')
print(f'Array x_float has data type {x_float.dtype}')

Array x_int has data type int32
Array x_float has data type float32


In [11]:
# Crate a 3D array.
x_3d = np.array([[[1, 2, 3, 4], [4, 7, 1, 9], [0, 4, 6, 8]], 
                 [[5, 2, 8, 0], [2, 4, 3, 1], [1, 0, 4, 9]]])

# Check the number of dimensions, number of elements, shape, and data type.
print(f'Number of dimensions: {x_3d.ndim}')
print(f'Number of elements: {x_3d.size}')
print(f'Shape: {x_3d.shape}')
print(f'Data type: {x_3d.dtype}')

# Simply print the array.
print(x_3d)

Number of dimensions: 3
Number of elements: 24
Shape: (2, 3, 4)
Data type: int32
[[[1 2 3 4]
  [4 7 1 9]
  [0 4 6 8]]

 [[5 2 8 0]
  [2 4 3 1]
  [1 0 4 9]]]


In [12]:
# Create a 2D array filled with a sequence of numbers.
x_seq_2d = np.arange(12).reshape(4, 3)

# Create a 3D array filled with ones, last axis computed automatically.
x_ones_3d = np.ones(8).reshape((2, 2, -1))

# Print the results.
print(f'x_seq_2d:\n{x_seq_2d}\n')
print(f'x_ones_3d:\n{x_ones_3d}\n')

x_seq_2d:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

x_ones_3d:
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]



In [24]:
#Exercice 2.5
## Create a 1D array of 10 elements of type float32 filled with a value 3.14.
## Hint: Use np.ones or np.full.

array_pi = np.full((1,10),3.14).astype(np.float32)
print(f'array_pi:\n{array_pi}\n')


array_pi:
[[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]]



In [36]:
## Find number of elements in the following array without using `size` property.
## Hint: Use np.prod.
x = np.zeros((4, 5, 6, 7, 8))
num_elements = x.size
print(f'Number of elements in x: {num_elements}')

Number of elements in x: 6720


In [46]:
## Reshape the 3D array "x_unknown" to a 1D array. Note that you do not know the shape of the array.
## Hint: You can access the shape property, use the `-1` trick, or function np.ndarray.flatten()
## (i.e. you have to call it s a function of the array, x.flatten())
x_unknown = np.zeros(np.random.randint(1, 5, 6))
x_flat =
print(f'Shape of x_flat: {x_flat.shape}')

AttributeError: 'bool' object has no attribute 'ndim'